services:
  web:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php84_apache
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html
      - ./apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    networks:
      - app_network
    restart: unless-stopped

  db:
    image: mysql:8
    container_name: mysql8_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fr
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app_network
    restart: unless-stopped

volumes:
  db_data:

networks:
  app_network:
    driver: bridge